# Generated by Django 2.0.5 on 2018-08-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_last_updated_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_time',
        ),
    ]
