# Generated by Django 2.0.5 on 2018-08-19 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
    ]
